[project]
name = "infrastructure"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.12.0",
    "httpx>=0.28.1",
    "modal>=1.2.0",
    "numpy>=2.2.6",
    "orjson>=3.11.3",
    "pandas>=2.3.3",
    "torch>=2.8.0",
    "transformers>=4.57.1",
    "vllm>=0.11.0",
]
